### ISSUE TITLE
Add changelog please

### ISSUE THREAD

**Issue by gdubicki** [jeff-hykin/ez_yaml#2]
Hi! 

I started to use your project in mine and I recently got pinged by dependabot about your new release - https://github.com/gdubicki/gitlabform/pull/347.

However it's very hard for me to check what has changed between 1.1.0 and 1.2.0 as you don't have a changelog and don't use tags or GitHub releases.

Would you be so kind to start using at least one of these things? It would be great if you could add it retroactively at least for 1.1.0 and 1.2.0 releases. :)

**Comment by jeff-hykin** [comment]
Took a while but finally added a changelog file. All versions from here forward (and some previous ones) are also git-tagged
